# [global]

# dataFrameSerialization = "legacy"

# [theme] # Theme
#                primaryColor = "#f63366"
#             backgroundColor = "#282a36"
#    secondaryBackgroundColor = "#44475a"
#                   textColor = "#f8f8f2"
#                        font = "sans-serif